######################################################################
# This code is used to generate D_Sigma for the simulation study.
# The construction is based on the representation D = 2A + B,
# where A and B are two-level regular designs (B may be degenerate).
# See He, Cheng, and Tang (2018) for details.
#
# Repeated executions of this code may return different arrays if the
# seed is changed or removed, but the resulting designs have the same
# Sigma pattern.
######################################################################

# If the script is run from a subfolder, move the working directory
# back to the repository root. We allow at most two upward moves.
n_up <- 0

while (
  !(dir.exists("R") && dir.exists("data")) &&
  dirname(getwd()) != getwd() &&
  n_up < 2
) {
  setwd("..")
  n_up <- n_up + 1
}

if (!(dir.exists("R") && dir.exists("data"))) {
  stop(
    "Could not locate the repository root. ",
    "Please set the working directory to the repository root ",
    "or to a subfolder within it."
  )
}

# Set a seed so that the generated D_Sigma.rds is reproducible.
set.seed(12345)

# All 2^5 binary vectors, viewed as the vector space GF(2)^5
F25 <- as.matrix(expand.grid(rep(list(0:1), 5)))

# Generating matrices of A and B
gen_A <- t(F25[c(1, 2, 4, 8, 3, 5, 9, 6, 10, 12, 7, 11, 27, 14, 30) + 1, ])
gen_B <- t(F25[c(21, 15, 28, 31, 20, 28, 17, 16, 16, 31, 26, 18, 13, 19, 15) + 1, ])

# The regular designs A and B generated by gen_A and gen_B, respectively
A <- (F25 %*% gen_A) %% 2
B <- (F25 %*% gen_B) %% 2

random_relabel <- function(d) {
  # This function randomly applies a restricted level permutation to a 4-level array.
  # The relabeling preserves the SP/Sigma pattern while increasing design diversity.
  for (j in 1:ncol(d)) {
    coin <- sample(0:1, 1)
    if (coin == 1) d[, j] <- 3 - d[, j]
  }
  
  for (j in 1:ncol(d)) {
    idx_0 <- which(d[, j] == 0)
    idx_1 <- which(d[, j] == 1)
    coin <- sample(0:1, 1)
    
    if (coin == 1) {
      d[idx_0, j] <- 1
      d[idx_1, j] <- 0
    }
  }
  
  for (j in 1:ncol(d)) {
    idx_2 <- which(d[, j] == 2)
    idx_3 <- which(d[, j] == 3)
    coin <- sample(0:1, 1)
    
    if (coin == 1) {
      d[idx_2, j] <- 3
      d[idx_3, j] <- 2
    }
  }
  
  return(d)
}

D_Sigma <- 2 * A + B
D_Sigma <- random_relabel(D_Sigma)

# Save the fixed design used in the simulation study.
if (!dir.exists("data")) {
  dir.create("data")
}

saveRDS(D_Sigma, "data/D_Sigma.rds")