######################################################################
# This code is used to generate D_SP for the simulation study.
# The construction is based on the representation D = 2A + B,
# where A and B are two-level regular designs (B may be degenerate).
# See He, Cheng, and Tang (2018) for details.
#
# In the present 32-run, 15-factor setting,
# A must be chosen as the maximal even design with one column dropped;
# otherwise D = 2A + B cannot be SP-optimal.
# After fixing A, B must be selected from an admissible class.
#
# Repeated executions of this code may return different arrays if the
# seed is changed or removed, but the resulting designs have the same
# SP pattern.
######################################################################

# If the script is run from a subfolder, move the working directory
# back to the repository root. We allow at most two upward moves.
n_up <- 0

while (
  !(dir.exists("R") && dir.exists("data")) &&
  dirname(getwd()) != getwd() &&
  n_up < 2
) {
  setwd("..")
  n_up <- n_up + 1
}

if (!(dir.exists("R") && dir.exists("data"))) {
  stop(
    "Could not locate the repository root. ",
    "Please set the working directory to the repository root ",
    "or to a subfolder within it."
  )
}

# Set a seed so that the generated D_SP.rds is reproducible.
set.seed(12345)

# All 2^5 binary vectors, viewed as the vector space GF(2)^5
F25 <- as.matrix(expand.grid(rep(list(0:1), 5)))

# Generating matrix of A
gen_A <- t(F25[18:32, ])

# The regular design A generated by gen_A,
# which is the maximal even design with one column dropped.
A <- (F25 %*% gen_A) %% 2

# The complement of gen_A, used to construct admissible B
c_gen_A <- t(F25[2:17, ])

construct_D_SP <- function() {
  # Randomly construct an admissible B after A is fixed.
  idx <- rep(1, 15)
  coin <- sample(0:1, 15, replace = TRUE)
  idx[coin == 1] <- 16
  
  gen_B <- c_gen_A[, idx]
  B <- (F25 %*% gen_B) %% 2
  
  D_SP <- 2 * A + B
  return(D_SP)
}

random_relabel <- function(d) {
  # This function randomly applies a restricted level permutation to a 4-level array.
  # The relabeling preserves the SP/Sigma pattern while increasing design diversity.
  for (j in 1:ncol(d)) {
    coin <- sample(0:1, 1)
    if (coin == 1) d[, j] <- 3 - d[, j]
  }
  
  for (j in 1:ncol(d)) {
    idx_0 <- which(d[, j] == 0)
    idx_1 <- which(d[, j] == 1)
    coin <- sample(0:1, 1)
    
    if (coin == 1) {
      d[idx_0, j] <- 1
      d[idx_1, j] <- 0
    }
  }
  
  for (j in 1:ncol(d)) {
    idx_2 <- which(d[, j] == 2)
    idx_3 <- which(d[, j] == 3)
    coin <- sample(0:1, 1)
    
    if (coin == 1) {
      d[idx_2, j] <- 3
      d[idx_3, j] <- 2
    }
  }
  
  return(d)
}

D_SP <- construct_D_SP()
D_SP <- random_relabel(D_SP)

# Save the fixed design used in the simulation study.
if (!dir.exists("data")) {
  dir.create("data")
}

saveRDS(D_SP, "data/D_SP.rds")